language: cpp
os: linux
dist: bionic
jobs:
- arch: amd64
  env: ARCH_SUB="x86_64"
install:
- sudo apt update
- sudo apt install qt5-default qttools5-dev-tools libgl1-mesa-dev git wget -y 
script:
- qmake && make 
- bash scripts/packaging.sh
deploy:
  provider: releases
  api_key:
    secure: "gBxw8hWb+Gin5no5RFBgNzscERXX0sX2WoJwjwqjv9c6HRevicxb6jYGRLSP6/7EkBzXNCzv9rZqGahpuwmgLgs8v8bDxhl6LoRoCbVW9gVumvkBe5rgrRVLNTjIiafnf22o2j2lndRdvwy8YYK51vmy3nQJtBSIN+Y09bVj8fCJElN2N/   C3tKgq7IhbSzFubCxVwEQyhhUy8TmxtfUTIvmJxiELT7111/+cNQY/kLvpZgME8HWLcewrWQt5NwW/K8HGcL2nl+gBnHplxHCROvUVGB21l7qBfKw3UqgE9grXde+8N29B+wkZpG0scO+Xl0+2mUwp3QAoEhsd4i7NQmp0uBzc+k3flGcRMEUK8PyjdEyHCbTn5gm2FolvMvV+lKNZcb2zpLMTYqgNoP/MWKVSwueRKZO2sB05Oj4c/vbORWkbtmb9xY49Az8FH44qTajECmfaDPftpp08ngdWJLS66cM4k9wxXjuuZF4/fqBoPmjG1WwyKt/cxiujB8jLT8QGy4CNV8/hmP5cSH2ZdDSdV+wTbWaLqqy3r+F42/3RkcJCNuawNu9p9ZXb/Bm4UhLcqmzpIRPDgopHjJ5d4UoIABV1X0fd9OA2mB02c6ISIgUlUQ8gTjNwjlHVTcERc/j0cLVHgnnFwdgbb2P2cKIrACPGq3NjHWtQPQ+reQQ="
  file: helloworld-gui-${TRAVIS_TAG}_${TRAVIS_CPU_ARCH}.tar.gz
  on:
    repo: enjoysoftware/helloworld-gui
    tags: true
  skip_cleanup: 'true'
